services:
  webswing_chat:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: chat_app_dev
    ports:
      - "8080:8080" 
    volumes:
      - ./logs:/opt/webswing/logs